# Generated by Django 5.2.17 on 2026-08-22 14:22

import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('node_type', django_enum.fields.EnumCharField(choices=[('business_outcome', 'Business outcome'), ('user_role', 'User role'), ('data_product', 'Data product'), ('system', 'System'), ('connector', 'Connector'), ('tool', 'Tool'), ('agent_capability', 'Agent capability'), ('agent_instance', 'Agent instance'), ('workflow', 'Workflow'), ('control', 'Control'), ('delivery_artifact', 'Delivery artifact')], max_length=40)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=180)),
                ('classification', django_enum.fields.EnumCharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], max_length=24)),
                ('approval_state', django_enum.fields.EnumCharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('conditional', 'Conditionally approved'), ('retired', 'Retired')], max_length=24)),
                ('source_reference', models.CharField(blank=True, max_length=220)),
            ],
            options={
                'db_table': 'studio_ontology_nodes',
                'ordering': ('node_type', 'name'),
                'indexes': [models.Index(fields=['node_type', 'approval_state'], name='studio_onto_node_ty_be0c7f_idx'), models.Index(fields=['classification'], name='studio_onto_classif_c56865_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('node_type__in', ['business_outcome', 'user_role', 'data_product', 'system', 'connector', 'tool', 'agent_capability', 'agent_instance', 'workflow', 'control', 'delivery_artifact'])), name='studio_OntologyNode_node_type_NodeType'), models.CheckConstraint(condition=models.Q(('classification__in', ['public', 'internal', 'confidential', 'restricted'])), name='studio_OntologyNode_classification_Classification'), models.CheckConstraint(condition=models.Q(('approval_state__in', ['draft', 'approved', 'conditional', 'retired'])), name='studio_OntologyNode_approval_state_ApprovalState')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=180)),
                ('intent', models.TextField()),
                ('requester_role', models.CharField(max_length=160)),
                ('business_outcome', models.TextField()),
                ('summary', models.TextField()),
                ('status', django_enum.fields.EnumCharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs review'), ('approved', 'Approved for sandbox'), ('blocked', 'Blocked')], max_length=24)),
                ('risk_level', django_enum.fields.EnumCharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=24)),
                ('model_provider', models.CharField(max_length=40)),
                ('model_name', models.CharField(max_length=100)),
                ('model_used', models.BooleanField(default=False)),
                ('existing_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals_reusing_workflow', to='studio.ontologynode')),
            ],
            options={
                'db_table': 'studio_workflow_proposals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProposalBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('binding_kind', django_enum.fields.EnumCharField(choices=[('data', 'Data binding'), ('tool', 'Tool binding'), ('agent', 'Agent binding'), ('control', 'Control binding'), ('delivery', 'Delivery binding')], max_length=24)),
                ('access_mode', django_enum.fields.EnumCharField(choices=[('read', 'Read only'), ('invoke', 'Invoke'), ('enforce', 'Enforce'), ('generate', 'Generate draft')], max_length=24)),
                ('purpose', models.TextField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_bindings', to='studio.ontologynode')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='studio.workflowproposal')),
            ],
            options={
                'db_table': 'studio_proposal_bindings',
                'ordering': ('binding_kind', 'node__name'),
            },
        ),
        migrations.CreateModel(
            name='ProofEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', django_enum.fields.EnumCharField(choices=[('intent_captured', 'Intent captured'), ('model_invoked', 'Model invoked'), ('model_bypassed', 'Model bypassed'), ('ontology_matched', 'Ontology matched'), ('policy_checked', 'Policy checked'), ('human_approved', 'Human approved'), ('sdlc_package_ready', 'SDLC package ready')], max_length=32)),
                ('actor', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('evidence_reference', models.CharField(max_length=180)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_events', to='studio.workflowproposal')),
            ],
            options={
                'db_table': 'studio_proof_events',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ControlCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=180)),
                ('outcome', django_enum.fields.EnumCharField(choices=[('pass', 'Pass'), ('warning', 'Warning'), ('block', 'Block')], max_length=24)),
                ('detail', models.TextField()),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_checks', to='studio.ontologynode')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_checks', to='studio.workflowproposal')),
            ],
            options={
                'db_table': 'studio_control_checks',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OntologyEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('relation', django_enum.fields.EnumCharField(choices=[('serves', 'Serves'), ('used_by', 'Used by'), ('uses', 'Uses'), ('reads', 'Reads'), ('resides_in', 'Resides in'), ('exposes', 'Exposes'), ('invokes', 'Invokes'), ('instance_of', 'Instance of'), ('constrained_by', 'Constrained by'), ('requires', 'Requires'), ('produces', 'Produces'), ('implements', 'Implements')], max_length=32)),
                ('rationale', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='studio.ontologynode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='studio.ontologynode')),
            ],
            options={
                'db_table': 'studio_ontology_edges',
                'ordering': ('source__name', 'relation', 'target__name'),
                'indexes': [models.Index(fields=['relation'], name='studio_onto_relatio_af9c94_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'relation', 'target'), name='unique_ontology_edge'), models.CheckConstraint(condition=models.Q(('relation__in', ['serves', 'used_by', 'uses', 'reads', 'resides_in', 'exposes', 'invokes', 'instance_of', 'constrained_by', 'requires', 'produces', 'implements'])), name='studio_OntologyEdge_relation_RelationType')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowproposal',
            index=models.Index(fields=['status', 'created_at'], name='studio_work_status_7bffd9_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowproposal',
            index=models.Index(fields=['risk_level'], name='studio_work_risk_le_f228f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowproposal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'needs_review', 'approved', 'blocked'])), name='studio_WorkflowProposal_status_ProposalStatus'),
        ),
        migrations.AddConstraint(
            model_name='workflowproposal',
            constraint=models.CheckConstraint(condition=models.Q(('risk_level__in', ['low', 'moderate', 'high'])), name='studio_WorkflowProposal_risk_level_RiskLevel'),
        ),
        migrations.AddConstraint(
            model_name='proposalbinding',
            constraint=models.UniqueConstraint(fields=('proposal', 'node', 'binding_kind'), name='unique_proposal_binding'),
        ),
        migrations.AddConstraint(
            model_name='proposalbinding',
            constraint=models.CheckConstraint(condition=models.Q(('binding_kind__in', ['data', 'tool', 'agent', 'control', 'delivery'])), name='studio_ProposalBinding_binding_kind_BindingKind'),
        ),
        migrations.AddConstraint(
            model_name='proposalbinding',
            constraint=models.CheckConstraint(condition=models.Q(('access_mode__in', ['read', 'invoke', 'enforce', 'generate'])), name='studio_ProposalBinding_access_mode_AccessMode'),
        ),
        migrations.AddIndex(
            model_name='proofevent',
            index=models.Index(fields=['event_type', 'created_at'], name='studio_proo_event_t_42cb8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='proofevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['intent_captured', 'model_invoked', 'model_bypassed', 'ontology_matched', 'policy_checked', 'human_approved', 'sdlc_package_ready'])), name='studio_ProofEvent_event_type_ProofEventType'),
        ),
        migrations.AddConstraint(
            model_name='controlcheck',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['pass', 'warning', 'block'])), name='studio_ControlCheck_outcome_CheckOutcome'),
        ),
    ]
