# Generated by Django 5.2.17 on 2026-08-23 02:32

import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
from django.db import migrations, models


class CommentedAlterField(migrations.AlterField):
    """Persist comment metadata without rebuilding tables on unsupported databases."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.features.supports_comments:
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.features.supports_comments:
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0003_neutralize_platform_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controlcheck",
            options={
                "ordering": ("created_at",),
                "verbose_name": "control check",
                "verbose_name_plural": "control checks",
            },
        ),
        migrations.AlterModelOptions(
            name="ontologyedge",
            options={
                "ordering": ("source__name", "relation", "target__name"),
                "verbose_name": "ontology relationship",
                "verbose_name_plural": "ontology relationships",
            },
        ),
        migrations.AlterModelOptions(
            name="ontologynode",
            options={
                "ordering": ("node_type", "name"),
                "verbose_name": "ontology concept",
                "verbose_name_plural": "ontology concepts",
            },
        ),
        migrations.AlterModelOptions(
            name="proofevent",
            options={
                "ordering": ("created_at",),
                "verbose_name": "proof event",
                "verbose_name_plural": "proof events",
            },
        ),
        migrations.AlterModelOptions(
            name="proposalbinding",
            options={
                "ordering": ("binding_kind", "node__name"),
                "verbose_name": "proposal binding",
                "verbose_name_plural": "proposal bindings",
            },
        ),
        migrations.AlterModelOptions(
            name="workflowproposal",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "workflow proposal",
                "verbose_name_plural": "workflow proposals",
            },
        ),
        migrations.AlterModelTableComment(
            name="controlcheck",
            table_comment="Deterministic governance results produced while evaluating workflow proposals.",
        ),
        migrations.AlterModelTableComment(
            name="ontologyedge",
            table_comment="Typed directed relationships that connect governed ontology concepts.",
        ),
        migrations.AlterModelTableComment(
            name="ontologynode",
            table_comment="Governed ontology concepts available for workflow design and review.",
        ),
        migrations.AlterModelTableComment(
            name="proofevent",
            table_comment="Append-only, non-sensitive evidence for workflow proposal lifecycle events.",
        ),
        migrations.AlterModelTableComment(
            name="proposalbinding",
            table_comment="Governed ontology concepts selected as dependencies of workflow proposals.",
        ),
        migrations.AlterModelTableComment(
            name="workflowproposal",
            table_comment="Reviewable workflow and agent specifications derived from business intent.",
        ),
        CommentedAlterField(
            model_name="controlcheck",
            name="control",
            field=models.ForeignKey(
                blank=True,
                db_comment="Optional ontology control that defines this check.",
                help_text="Registered control represented by this result, when applicable.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="control_checks",
                to="studio.ontologynode",
            ),
        ),
        CommentedAlterField(
            model_name="controlcheck",
            name="created_at",
            field=models.DateTimeField(
                db_comment="Timestamp when this record was created.",
                default=django.utils.timezone.now,
                help_text="Date and time when the record was created.",
            ),
        ),
        CommentedAlterField(
            model_name="controlcheck",
            name="detail",
            field=models.TextField(
                db_comment="Reviewable explanation of the control-check outcome.",
                help_text="Explain the evidence and rule that produced this outcome.",
            ),
        ),
        CommentedAlterField(
            model_name="controlcheck",
            name="id",
            field=models.BigAutoField(
                db_comment="Surrogate primary key for this record.",
                help_text="System-assigned record identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        CommentedAlterField(
            model_name="controlcheck",
            name="name",
            field=models.CharField(
                db_comment="Human-readable name of the deterministic control check.",
                help_text="Concise name shown to proposal reviewers.",
                max_length=180,
            ),
        ),
        CommentedAlterField(
            model_name="controlcheck",
            name="outcome",
            field=django_enum.fields.EnumCharField(
                choices=[("pass", "Pass"), ("warning", "Warning"), ("block", "Block")],
                db_comment="Deterministic outcome returned by the control check.",
                help_text="Whether the proposal passed, raised a warning, or was blocked.",
                max_length=24,
            ),
        ),
        CommentedAlterField(
            model_name="controlcheck",
            name="proposal",
            field=models.ForeignKey(
                db_comment="Workflow proposal evaluated by this deterministic control check.",
                help_text="Proposal whose policy conformance was evaluated.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="control_checks",
                to="studio.workflowproposal",
            ),
        ),
        CommentedAlterField(
            model_name="ontologyedge",
            name="created_at",
            field=models.DateTimeField(
                db_comment="Timestamp when this record was created.",
                default=django.utils.timezone.now,
                help_text="Date and time when the record was created.",
            ),
        ),
        CommentedAlterField(
            model_name="ontologyedge",
            name="id",
            field=models.BigAutoField(
                db_comment="Surrogate primary key for this record.",
                help_text="System-assigned record identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        CommentedAlterField(
            model_name="ontologyedge",
            name="rationale",
            field=models.TextField(
                blank=True,
                db_comment="Optional explanation supporting the ontology relationship.",
                help_text="Explain why this relationship exists or cite its governing source.",
            ),
        ),
        CommentedAlterField(
            model_name="ontologyedge",
            name="relation",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("serves", "Serves"),
                    ("used_by", "Used by"),
                    ("uses", "Uses"),
                    ("reads", "Reads"),
                    ("resides_in", "Resides in"),
                    ("exposes", "Exposes"),
                    ("invokes", "Invokes"),
                    ("instance_of", "Instance of"),
                    ("constrained_by", "Constrained by"),
                    ("requires", "Requires"),
                    ("produces", "Produces"),
                    ("implements", "Implements"),
                ],
                db_comment="Semantic type of the directed ontology relationship.",
                help_text="Describe how the source concept relates to the target concept.",
                max_length=32,
            ),
        ),
        CommentedAlterField(
            model_name="ontologyedge",
            name="source",
            field=models.ForeignKey(
                db_comment="Ontology concept where this directed relationship begins.",
                help_text="Concept that acts as the source of the relationship.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_edges",
                to="studio.ontologynode",
            ),
        ),
        CommentedAlterField(
            model_name="ontologyedge",
            name="target",
            field=models.ForeignKey(
                db_comment="Ontology concept where this directed relationship ends.",
                help_text="Concept that acts as the target of the relationship.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_edges",
                to="studio.ontologynode",
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="approval_state",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("draft", "Draft"),
                    ("approved", "Approved"),
                    ("conditional", "Conditionally approved"),
                    ("retired", "Retired"),
                ],
                db_comment="Governance approval state of the ontology concept.",
                help_text="Controls whether the concept can be selected for a proposal.",
                max_length=24,
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="classification",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("public", "Public"),
                    ("internal", "Internal"),
                    ("confidential", "Confidential"),
                    ("restricted", "Restricted"),
                ],
                db_comment="Information-sensitivity classification of the concept.",
                help_text="Highest sensitivity level associated with using this concept.",
                max_length=24,
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="created_at",
            field=models.DateTimeField(
                db_comment="Timestamp when this record was created.",
                default=django.utils.timezone.now,
                help_text="Date and time when the record was created.",
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="description",
            field=models.TextField(
                db_comment="Plain-language definition and scope of the ontology concept.",
                help_text="Explain what the concept represents and where its responsibility ends.",
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="id",
            field=models.BigAutoField(
                db_comment="Surrogate primary key for this record.",
                help_text="System-assigned record identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="name",
            field=models.CharField(
                db_comment="Human-readable name of the ontology concept.",
                help_text="Concise name shown throughout the catalog and proposal views.",
                max_length=180,
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="node_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("business_outcome", "Business outcome"),
                    ("user_role", "User role"),
                    ("data_product", "Data product"),
                    ("system", "System"),
                    ("connector", "Connector"),
                    ("tool", "Tool"),
                    ("agent_capability", "Agent capability"),
                    ("agent_instance", "Agent instance"),
                    ("workflow", "Workflow"),
                    ("control", "Control"),
                    ("delivery_artifact", "Delivery artifact"),
                ],
                db_comment="Ontology category assigned to the concept.",
                help_text="Select the concept's role in the governed ontology.",
                max_length=40,
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="owner",
            field=models.CharField(
                db_comment="Accountable organizational owner of the ontology concept.",
                help_text="Team or function accountable for approving and maintaining this concept.",
                max_length=180,
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="slug",
            field=models.SlugField(
                db_comment="Stable machine-readable identifier for the ontology concept.",
                help_text="Stable identifier used in catalog references and proposal payloads.",
                max_length=100,
                unique=True,
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="source_reference",
            field=models.CharField(
                blank=True,
                db_comment="Optional reference to the authoritative source or registry entry.",
                help_text="Name or locator of the authoritative source for this concept, when known.",
                max_length=220,
            ),
        ),
        CommentedAlterField(
            model_name="ontologynode",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="Timestamp when this record was last updated.",
                default=django.utils.timezone.now,
                help_text="Date and time of the most recent saved change.",
            ),
        ),
        CommentedAlterField(
            model_name="proofevent",
            name="actor",
            field=models.CharField(
                db_comment="Human role or system component responsible for the event.",
                help_text="Accountable person, role, or service that performed the recorded action.",
                max_length=120,
            ),
        ),
        CommentedAlterField(
            model_name="proofevent",
            name="created_at",
            field=models.DateTimeField(
                db_comment="Timestamp when this record was created.",
                default=django.utils.timezone.now,
                help_text="Date and time when the record was created.",
            ),
        ),
        CommentedAlterField(
            model_name="proofevent",
            name="event_type",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("intent_captured", "Intent captured"),
                    ("model_invoked", "Model invoked"),
                    ("model_bypassed", "Model bypassed"),
                    ("ontology_matched", "Ontology matched"),
                    ("policy_checked", "Policy checked"),
                    ("human_approved", "Human approved"),
                    ("sdlc_package_ready", "SDLC package ready"),
                ],
                db_comment="Lifecycle event category represented by this proof record.",
                help_text="Auditable stage of proposal processing represented by this event.",
                max_length=32,
            ),
        ),
        CommentedAlterField(
            model_name="proofevent",
            name="evidence_reference",
            field=models.CharField(
                db_comment="Stable reference used to correlate supporting evidence.",
                help_text="Non-secret identifier linking this event to its supporting evidence.",
                max_length=180,
            ),
        ),
        CommentedAlterField(
            model_name="proofevent",
            name="id",
            field=models.BigAutoField(
                db_comment="Surrogate primary key for this record.",
                help_text="System-assigned record identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        CommentedAlterField(
            model_name="proofevent",
            name="proposal",
            field=models.ForeignKey(
                db_comment="Workflow proposal whose lifecycle produced this proof event.",
                help_text="Proposal associated with this append-only evidence record.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proof_events",
                to="studio.workflowproposal",
            ),
        ),
        CommentedAlterField(
            model_name="proofevent",
            name="summary",
            field=models.TextField(
                db_comment="Non-sensitive explanation of the lifecycle event.",
                help_text="Describe what occurred without storing secrets or raw provider payloads.",
            ),
        ),
        CommentedAlterField(
            model_name="proposalbinding",
            name="access_mode",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("read", "Read only"),
                    ("invoke", "Invoke"),
                    ("enforce", "Enforce"),
                    ("generate", "Generate draft"),
                ],
                db_comment="Permitted interaction mode for the bound ontology concept.",
                help_text="Maximum action the proposed workflow may take through this binding.",
                max_length=24,
            ),
        ),
        CommentedAlterField(
            model_name="proposalbinding",
            name="binding_kind",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("data", "Data binding"),
                    ("tool", "Tool binding"),
                    ("agent", "Agent binding"),
                    ("control", "Control binding"),
                    ("delivery", "Delivery binding"),
                ],
                db_comment="Functional role of the ontology concept within the proposal.",
                help_text="How the selected concept participates in the proposed workflow.",
                max_length=24,
            ),
        ),
        CommentedAlterField(
            model_name="proposalbinding",
            name="created_at",
            field=models.DateTimeField(
                db_comment="Timestamp when this record was created.",
                default=django.utils.timezone.now,
                help_text="Date and time when the record was created.",
            ),
        ),
        CommentedAlterField(
            model_name="proposalbinding",
            name="id",
            field=models.BigAutoField(
                db_comment="Surrogate primary key for this record.",
                help_text="System-assigned record identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        CommentedAlterField(
            model_name="proposalbinding",
            name="node",
            field=models.ForeignKey(
                db_comment="Governed ontology concept bound into the workflow proposal.",
                help_text="Approved or conditional catalog concept used by the proposal.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proposal_bindings",
                to="studio.ontologynode",
            ),
        ),
        CommentedAlterField(
            model_name="proposalbinding",
            name="proposal",
            field=models.ForeignKey(
                db_comment="Workflow proposal that owns this ontology binding.",
                help_text="Proposal whose design depends on the selected ontology concept.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bindings",
                to="studio.workflowproposal",
            ),
        ),
        CommentedAlterField(
            model_name="proposalbinding",
            name="purpose",
            field=models.TextField(
                db_comment="Proposal-specific reason for including the ontology concept.",
                help_text="Explain why this binding is necessary for the proposed outcome.",
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="business_outcome",
            field=models.TextField(
                db_comment="Normalized business outcome derived from the submitted intent.",
                help_text="Plain-language outcome the proposed workflow is expected to support.",
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="created_at",
            field=models.DateTimeField(
                db_comment="Timestamp when this record was created.",
                default=django.utils.timezone.now,
                help_text="Date and time when the record was created.",
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="existing_workflow",
            field=models.ForeignKey(
                blank=True,
                db_comment="Optional registered workflow selected as the proposal extension point.",
                help_text="Existing approved workflow to extend instead of creating a new one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proposals_reusing_workflow",
                to="studio.ontologynode",
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="id",
            field=models.BigAutoField(
                db_comment="Surrogate primary key for this record.",
                help_text="System-assigned record identifier.",
                primary_key=True,
                serialize=False,
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="intent",
            field=models.TextField(
                db_comment="Original business intent submitted by the requester.",
                help_text="The request supplied for interpretation and proposal composition.",
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="model_name",
            field=models.CharField(
                db_comment="Model identifier selected for proposal composition.",
                help_text="Model name requested from the selected provider route.",
                max_length=100,
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="model_provider",
            field=models.CharField(
                db_comment="Provider route selected for proposal composition.",
                help_text="Provider route used or selected when the proposal was composed.",
                max_length=40,
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="model_used",
            field=models.BooleanField(
                db_comment="Whether an external language model processed the submitted intent.",
                default=False,
                help_text="Indicates whether composition invoked an external model.",
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="requester_role",
            field=models.CharField(
                db_comment="Business role accountable for submitting the proposal intent.",
                help_text="Role or function requesting the governed workflow.",
                max_length=160,
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="risk_level",
            field=django_enum.fields.EnumCharField(
                choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High")],
                db_comment="Calculated risk tier used to route proposal review.",
                help_text="Risk tier derived from requested actions and bound data classifications.",
                max_length=24,
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("draft", "Draft"),
                    ("needs_review", "Needs review"),
                    ("approved", "Approved for sandbox"),
                    ("blocked", "Blocked"),
                ],
                db_comment="Current governance lifecycle state of the workflow proposal.",
                help_text="Current review and sandbox-readiness state.",
                max_length=24,
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="summary",
            field=models.TextField(
                db_comment="Review summary of the proposed workflow and agent behavior.",
                help_text="Concise explanation for reviewers evaluating the proposal.",
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="title",
            field=models.CharField(
                db_comment="Human-readable title of the workflow proposal.",
                help_text="Short title that distinguishes this proposal in review lists.",
                max_length=180,
            ),
        ),
        CommentedAlterField(
            model_name="workflowproposal",
            name="updated_at",
            field=models.DateTimeField(
                db_comment="Timestamp when this record was last updated.",
                default=django.utils.timezone.now,
                help_text="Date and time of the most recent saved change.",
            ),
        ),
        migrations.AddIndex(
            model_name="controlcheck",
            index=models.Index(fields=["proposal", "outcome"], name="control_prop_outcome_idx"),
        ),
        migrations.AddIndex(
            model_name="proofevent",
            index=models.Index(fields=["proposal", "event_type"], name="proof_prop_event_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowproposal",
            index=models.Index(fields=["-created_at"], name="proposal_recent_idx"),
        ),
    ]
