# Generated by Django 5.2.17 on 2026-08-24 01:11

import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_model_documentation_and_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentManifest',
            fields=[
                ('id', models.BigAutoField(db_comment='Surrogate primary key for this record.', help_text='System-assigned record identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_comment='Timestamp when this record was created.', default=django.utils.timezone.now, help_text='Date and time when the record was created.')),
                ('version', models.CharField(db_comment='Semantic version assigned to the exported agent manifest.', help_text='Immutable semantic version for this manifest artifact.', max_length=32)),
                ('schema_version', models.CharField(db_comment='Version of the agent-manifest schema used by the artifact.', help_text='Schema contract understood by the mocked orchestration boundary.', max_length=48)),
                ('prompt_version', models.CharField(db_comment='Prompt contract version captured in the agent manifest.', help_text='Intent-interpretation prompt version associated with this specification.', max_length=80)),
                ('content', models.TextField(db_comment='Canonical JSON content of the versioned agent manifest.', help_text='Exact JSON bytes made available through the manifest download endpoint.')),
                ('artifact_hash', models.CharField(db_comment='SHA-256 digest of the canonical manifest content.', db_index=True, help_text='Integrity digest used to verify the downloaded manifest.', max_length=64)),
                ('size_bytes', models.PositiveIntegerField(db_comment='UTF-8 byte length of the canonical manifest content.', help_text='Size of the exported manifest artifact in bytes.')),
            ],
            options={
                'verbose_name': 'agent manifest',
                'verbose_name_plural': 'agent manifests',
                'db_table': 'studio_agent_manifests',
                'db_table_comment': 'Immutable, versioned agent manifests exported from governed proposals.',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(db_comment='Surrogate primary key for this record.', help_text='System-assigned record identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_comment='Timestamp when this record was created.', default=django.utils.timezone.now, help_text='Date and time when the record was created.')),
                ('test_case', django_enum.fields.EnumCharField(choices=[('citation_accuracy', 'Citation accuracy'), ('refusal', 'Unsafe-action refusal'), ('access_control', 'Access control'), ('prompt_injection', 'Prompt injection')], db_comment='Required evaluation scenario executed against the sandbox agent.', help_text='Citation, refusal, access-control, or prompt-injection test.', max_length=32)),
                ('outcome', django_enum.fields.EnumCharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], db_comment='Deterministic pass or fail outcome for the evaluation.', help_text='Whether observed sandbox behavior matched the expected result.', max_length=16)),
                ('score', models.DecimalField(db_comment='Normalized evaluation score between zero and one.', decimal_places=4, help_text='Machine-readable score used by the sandbox evaluation gate.', max_digits=5)),
                ('expected', models.TextField(db_comment='Expected behavior defined by the evaluation pack.', help_text='Reviewable success condition for this evaluation case.')),
                ('observed', models.TextField(db_comment='Observed synthetic behavior produced by the sandbox run.', help_text='Bounded evidence compared with the expected behavior.')),
                ('latency_ms', models.PositiveIntegerField(db_comment='Measured deterministic evaluation latency in milliseconds.', help_text='Elapsed time required to execute and score this test case.')),
                ('artifact_hash', models.CharField(db_comment='SHA-256 digest of the canonical evaluation result.', help_text='Integrity digest for the evaluation evidence record.', max_length=64)),
            ],
            options={
                'verbose_name': 'evaluation result',
                'verbose_name_plural': 'evaluation results',
                'db_table': 'studio_evaluation_results',
                'db_table_comment': 'Deterministic results for the required sandbox evaluation pack.',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceArtifact',
            fields=[
                ('id', models.BigAutoField(db_comment='Surrogate primary key for this record.', help_text='System-assigned record identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_comment='Timestamp when this record was created.', default=django.utils.timezone.now, help_text='Date and time when the record was created.')),
                ('artifact_type', django_enum.fields.EnumCharField(choices=[('evaluation_report', 'Evaluation report'), ('evidence_manifest', 'Evidence manifest')], db_comment='Semantic type of the generated evidence artifact.', help_text='Evaluation report or complete evidence manifest.', max_length=32)),
                ('version', models.CharField(db_comment='Semantic version assigned to the evidence artifact.', help_text='Immutable version of the generated evidence content.', max_length=32)),
                ('content', models.TextField(db_comment='Canonical JSON content of the evidence artifact.', help_text='Exact JSON bytes returned by the artifact download endpoint.')),
                ('artifact_hash', models.CharField(db_comment='SHA-256 digest of the canonical evidence content.', db_index=True, help_text='Integrity digest for independent artifact verification.', max_length=64)),
                ('size_bytes', models.PositiveIntegerField(db_comment='UTF-8 byte length of the canonical evidence content.', help_text='Size of the downloadable artifact in bytes.')),
            ],
            options={
                'verbose_name': 'evidence artifact',
                'verbose_name_plural': 'evidence artifacts',
                'db_table': 'studio_evidence_artifacts',
                'db_table_comment': 'Immutable, versioned JSON proof artifacts from sandbox evaluation.',
                'ordering': ('artifact_type', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InsuranceFinding',
            fields=[
                ('id', models.BigAutoField(db_comment='Surrogate primary key for this record.', help_text='System-assigned record identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_comment='Timestamp when this record was created.', default=django.utils.timezone.now, help_text='Date and time when the record was created.')),
                ('title', models.CharField(db_comment='Concise review title for the synthetic finding.', help_text='Short description displayed to the servicing reviewer.', max_length=180)),
                ('finding', models.TextField(db_comment='Synthetic evidence-based insurance observation.', help_text='Finding returned for human review without making a final determination.')),
                ('citations', models.TextField(db_comment='Canonical JSON list of citations grounding this finding.', help_text='Document, profile, and policy references supporting the observation.')),
                ('disposition', models.CharField(db_comment='Required downstream treatment of the synthetic finding.', default='human_review_required', help_text='Explicitly preserves human authority over the final determination.', max_length=64)),
            ],
            options={
                'verbose_name': 'insurance finding',
                'verbose_name_plural': 'insurance findings',
                'db_table': 'studio_insurance_findings',
                'db_table_comment': 'Synthetic cited findings produced during sandbox evaluation.',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProposalApproval',
            fields=[
                ('id', models.BigAutoField(db_comment='Surrogate primary key for this record.', help_text='System-assigned record identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_comment='Timestamp when this record was created.', default=django.utils.timezone.now, help_text='Date and time when the record was created.')),
                ('review_role', django_enum.fields.EnumCharField(choices=[('business_owner', 'Business owner'), ('source_owner', 'Source owner')], db_comment='Independent governance role represented by this decision.', help_text='Business-owner or source-owner responsibility represented by the reviewer.', max_length=32)),
                ('decision', django_enum.fields.EnumCharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], db_comment='Decision recorded by the accountable reviewer.', help_text='Reviewer decision for controlled sandbox registration.', max_length=24)),
                ('approver', models.CharField(db_comment='Named synthetic reviewer or accountable reviewing function.', help_text='Person or function accountable for this decision.', max_length=160)),
                ('note', models.TextField(blank=True, db_comment='Optional rationale supplied with the human decision.', help_text='Explain approval conditions or reasons for rejection.')),
            ],
            options={
                'verbose_name': 'proposal approval',
                'verbose_name_plural': 'proposal approvals',
                'db_table': 'studio_proposal_approvals',
                'db_table_comment': 'Independent business-owner and source-owner proposal decisions.',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SandboxAgentInstance',
            fields=[
                ('id', models.BigAutoField(db_comment='Surrogate primary key for this record.', help_text='System-assigned record identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_comment='Timestamp when this record was created.', default=django.utils.timezone.now, help_text='Date and time when the record was created.')),
                ('updated_at', models.DateTimeField(db_comment='Timestamp when this record was last updated.', default=django.utils.timezone.now, help_text='Date and time of the most recent saved change.')),
                ('external_id', models.CharField(db_comment='Synthetic agent identifier returned by mocked orchestration.', help_text='Sandbox-only identifier assigned by the orchestration adapter.', max_length=100, unique=True)),
                ('orchestration_request_id', models.CharField(db_comment='Correlation identifier returned by mocked orchestration.', help_text='Request identifier used to demonstrate the orchestration boundary.', max_length=100, unique=True)),
                ('environment', models.CharField(db_comment='Non-production environment where the agent was registered.', default='synthetic-sandbox', help_text='Explicit runtime environment; this demo only supports synthetic sandbox.', max_length=64)),
                ('status', django_enum.fields.EnumCharField(choices=[('registered', 'Registered in sandbox'), ('evaluation_passed', 'Sandbox evaluation passed'), ('evaluation_failed', 'Sandbox evaluation failed')], db_comment='Current sandbox registration or evaluation state.', help_text='Lifecycle state that can never represent production deployment.', max_length=32)),
            ],
            options={
                'verbose_name': 'sandbox agent instance',
                'verbose_name_plural': 'sandbox agent instances',
                'db_table': 'studio_sandbox_agent_instances',
                'db_table_comment': 'Sandbox-only agent registrations returned by mocked orchestration.',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ToolInvocation',
            fields=[
                ('id', models.BigAutoField(db_comment='Surrogate primary key for this record.', help_text='System-assigned record identifier.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_comment='Timestamp when this record was created.', default=django.utils.timezone.now, help_text='Date and time when the record was created.')),
                ('sequence', models.PositiveSmallIntegerField(db_comment='Ordered position of the call within the sandbox run.', help_text='Stable sequence number used to reconstruct the runtime trace.')),
                ('human_subject', models.CharField(db_comment='Simulated human identity on whose behalf the call was made.', help_text='Synthetic analyst identity evaluated by runtime policy.', max_length=160)),
                ('agent_subject', models.CharField(db_comment='Registered sandbox agent identity making the call.', help_text='Agent identity evaluated independently from the simulated human.', max_length=160)),
                ('resource', models.CharField(db_comment='Synthetic resource identifier requested through the tool.', help_text='Loan or policy resource used to demonstrate authorization.', max_length=160)),
                ('decision', django_enum.fields.EnumCharField(choices=[('allow', 'Allowed'), ('deny', 'Denied')], db_comment='Runtime policy result for this synthetic tool request.', help_text='Whether policy allowed or denied the tool call.', max_length=16)),
                ('policy_reason', models.TextField(db_comment='Deterministic explanation for the runtime policy decision.', help_text='Human-readable rule and identity result supporting the decision.')),
                ('response_summary', models.TextField(blank=True, db_comment='Non-sensitive summary returned by the synthetic tool.', help_text='Bounded synthetic result; denied calls contain no source data.')),
                ('citations', models.TextField(blank=True, db_comment='Canonical JSON list of source citations returned by the tool.', help_text='Machine-readable citations available to the finding generator.')),
                ('latency_ms', models.PositiveIntegerField(db_comment='Measured synthetic tool execution latency in milliseconds.', help_text='Elapsed time for policy evaluation and synthetic connector execution.')),
                ('request_hash', models.CharField(db_comment='SHA-256 digest of the canonical, non-secret tool request.', help_text='Integrity digest for reconstructing the request evidence.', max_length=64)),
                ('response_hash', models.CharField(db_comment='SHA-256 digest of the canonical bounded tool response.', help_text='Integrity digest proving the allowed or denied response content.', max_length=64)),
            ],
            options={
                'verbose_name': 'tool invocation',
                'verbose_name_plural': 'tool invocations',
                'db_table': 'studio_tool_invocations',
                'db_table_comment': 'Append-only synthetic tool traces with dual-identity policy evidence.',
                'ordering': ('sequence',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='proofevent',
            name='studio_ProofEvent_event_type_ProofEventType',
        ),
        migrations.AddField(
            model_name='workflowproposal',
            name='estimated_cost_usd',
            field=models.DecimalField(blank=True, db_comment='Estimated provider cost in US dollars for proposal composition.', decimal_places=6, help_text='Estimated composition cost; blank when the route has no stable price mapping.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='workflowproposal',
            name='input_tokens',
            field=models.PositiveIntegerField(db_comment='Provider-reported input token count for proposal composition.', default=0, help_text='Input tokens reported by the selected model provider, when available.'),
        ),
        migrations.AddField(
            model_name='workflowproposal',
            name='model_latency_ms',
            field=models.PositiveIntegerField(db_comment='Measured wall-clock latency of proposal composition in milliseconds.', default=0, help_text='Elapsed time spent composing the structured proposal.'),
        ),
        migrations.AddField(
            model_name='workflowproposal',
            name='output_tokens',
            field=models.PositiveIntegerField(db_comment='Provider-reported output token count for proposal composition.', default=0, help_text='Output tokens reported by the selected model provider, when available.'),
        ),
        migrations.AddField(
            model_name='workflowproposal',
            name='prompt_version',
            field=models.CharField(db_comment='Version of the bounded intent-interpretation prompt contract.', default='insurance-intent-v1.0.0', help_text='Version identifier for the prompt used to compose this proposal.', max_length=80),
        ),
        migrations.AlterField(
            model_name='proofevent',
            name='event_type',
            field=django_enum.fields.EnumCharField(choices=[('intent_captured', 'Intent captured'), ('model_invoked', 'Model invoked'), ('model_bypassed', 'Model bypassed'), ('ontology_matched', 'Ontology matched'), ('policy_checked', 'Policy checked'), ('human_approved', 'Human approved'), ('sdlc_package_ready', 'SDLC package ready'), ('manifest_exported', 'Manifest exported'), ('business_approved', 'Business owner approved'), ('source_approved', 'Source owner approved'), ('sandbox_registered', 'Sandbox agent registered'), ('tool_invoked', 'Synthetic tool invoked'), ('policy_decided', 'Runtime policy decided'), ('evaluation_completed', 'Evaluation completed'), ('sandbox_evaluation_passed', 'Sandbox evaluation passed')], db_comment='Lifecycle event category represented by this proof record.', help_text='Auditable stage of proposal processing represented by this event.', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='proofevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['intent_captured', 'model_invoked', 'model_bypassed', 'ontology_matched', 'policy_checked', 'human_approved', 'sdlc_package_ready', 'manifest_exported', 'business_approved', 'source_approved', 'sandbox_registered', 'tool_invoked', 'policy_decided', 'evaluation_completed', 'sandbox_evaluation_passed'])), name='studio_ProofEvent_event_type_ProofEventType'),
        ),
        migrations.AddField(
            model_name='agentmanifest',
            name='proposal',
            field=models.ForeignKey(db_comment='Workflow proposal represented by this versioned agent manifest.', help_text='Proposal from which the manifest was deterministically exported.', on_delete=django.db.models.deletion.CASCADE, related_name='manifests', to='studio.workflowproposal'),
        ),
        migrations.AddField(
            model_name='proposalapproval',
            name='proposal',
            field=models.ForeignKey(db_comment='Workflow proposal receiving this independent human decision.', help_text='Proposal reviewed by the accountable business or source owner.', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='studio.workflowproposal'),
        ),
        migrations.AddField(
            model_name='sandboxagentinstance',
            name='manifest',
            field=models.OneToOneField(db_comment='Versioned manifest registered with the mocked orchestration service.', help_text='Immutable agent specification used for this sandbox instance.', on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_instance', to='studio.agentmanifest'),
        ),
        migrations.AddField(
            model_name='insurancefinding',
            name='agent',
            field=models.ForeignKey(db_comment='Sandbox agent instance that produced this cited finding.', help_text='Evaluated sandbox instance responsible for the finding.', on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='studio.sandboxagentinstance'),
        ),
        migrations.AddField(
            model_name='evidenceartifact',
            name='agent',
            field=models.ForeignKey(db_comment='Sandbox agent instance whose run produced this artifact.', help_text='Evaluated instance represented by the downloadable evidence.', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_artifacts', to='studio.sandboxagentinstance'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='agent',
            field=models.ForeignKey(db_comment='Sandbox agent instance evaluated by this test case.', help_text='Registered instance whose behavior was evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to='studio.sandboxagentinstance'),
        ),
        migrations.AddField(
            model_name='toolinvocation',
            name='agent',
            field=models.ForeignKey(db_comment='Sandbox agent instance that requested the synthetic tool call.', help_text='Registered sandbox instance responsible for this invocation.', on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='studio.sandboxagentinstance'),
        ),
        migrations.AddField(
            model_name='toolinvocation',
            name='tool',
            field=models.ForeignKey(db_comment='Registered ontology tool invoked by the sandbox agent.', help_text='Approved catalog tool represented by this synthetic call.', on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_tool_invocations', to='studio.ontologynode'),
        ),
        migrations.AddConstraint(
            model_name='agentmanifest',
            constraint=models.UniqueConstraint(fields=('proposal', 'version'), name='unique_proposal_manifest_version'),
        ),
        migrations.AddIndex(
            model_name='proposalapproval',
            index=models.Index(fields=['review_role', 'decision'], name='studio_prop_review__4408b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposalapproval',
            constraint=models.UniqueConstraint(fields=('proposal', 'review_role'), name='unique_proposal_review_role'),
        ),
        migrations.AddConstraint(
            model_name='proposalapproval',
            constraint=models.CheckConstraint(condition=models.Q(('review_role__in', ['business_owner', 'source_owner'])), name='studio_ProposalApproval_review_role_ReviewRole'),
        ),
        migrations.AddConstraint(
            model_name='proposalapproval',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['approved', 'rejected'])), name='studio_ProposalApproval_decision_ReviewDecision'),
        ),
        migrations.AddIndex(
            model_name='sandboxagentinstance',
            index=models.Index(fields=['status', 'created_at'], name='studio_sand_status_dd308f_idx'),
        ),
        migrations.AddConstraint(
            model_name='sandboxagentinstance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['registered', 'evaluation_passed', 'evaluation_failed'])), name='studio_SandboxAgentInstance_status_SandboxStatus'),
        ),
        migrations.AddConstraint(
            model_name='evidenceartifact',
            constraint=models.UniqueConstraint(fields=('agent', 'artifact_type', 'version'), name='unique_agent_artifact_version'),
        ),
        migrations.AddConstraint(
            model_name='evidenceartifact',
            constraint=models.CheckConstraint(condition=models.Q(('artifact_type__in', ['evaluation_report', 'evidence_manifest'])), name='studio_EvidenceArtifact_artifact_type_EvidenceArtifactType'),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['outcome', 'test_case'], name='studio_eval_outcome_ea9ab9_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationresult',
            constraint=models.UniqueConstraint(fields=('agent', 'test_case'), name='unique_agent_evaluation_case'),
        ),
        migrations.AddConstraint(
            model_name='evaluationresult',
            constraint=models.CheckConstraint(condition=models.Q(('test_case__in', ['citation_accuracy', 'refusal', 'access_control', 'prompt_injection'])), name='studio_EvaluationResult_test_case_EvaluationCase'),
        ),
        migrations.AddConstraint(
            model_name='evaluationresult',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['pass', 'fail'])), name='studio_EvaluationResult_outcome_EvaluationOutcome'),
        ),
        migrations.AddIndex(
            model_name='toolinvocation',
            index=models.Index(fields=['agent', 'decision'], name='studio_tool_agent_i_0b4372_idx'),
        ),
        migrations.AddIndex(
            model_name='toolinvocation',
            index=models.Index(fields=['tool', 'created_at'], name='studio_tool_tool_id_c3ba4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='toolinvocation',
            constraint=models.UniqueConstraint(fields=('agent', 'sequence'), name='unique_agent_tool_sequence'),
        ),
        migrations.AddConstraint(
            model_name='toolinvocation',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['allow', 'deny'])), name='studio_ToolInvocation_decision_PolicyDecision'),
        ),
    ]
