# Generated by Django 5.2.17 on 2026-08-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_agentmanifest_evaluationresult_evidenceartifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowproposal',
            name='agent_name',
            field=models.CharField(db_comment='Human-readable name assigned to the proposed sandbox agent.', default='Insurance Covenant Review Agent', help_text='Agent name exported into the versioned sandbox manifest.', max_length=180),
        ),
    ]
