# Generated by Django 5.2.17 on 2026-08-26 18:13

import django_enum.fields
from django.db import migrations, models


DOMAIN_SLUGS = {
    "treasury_management": (
        "seismic-sales-content",
        "pinnacle-product-docs",
        "qvidian-proposal-library",
        "seismic-system",
        "pinnacle-system",
        "qvidian-system",
        "treasury-sales-assistant",
    ),
    "retail_banking": (
        "salesforce-edge",
        "salesforce-edge-system",
        "retail-care-center-assist",
    ),
    "commercial_loan_servicing": (
        "insurance-covenant-review",
        "servicing-analyst",
        "midland-loan-documents",
        "commercial-loan-profile",
        "insurance-policy-standards",
        "midland-file-source",
        "servicing-database",
        "policy-repository",
        "midland-document-connector",
        "servicing-api-connector",
        "policy-index-connector",
        "loan-document-search",
        "loan-profile-lookup",
        "policy-search",
        "grounded-covenant-analysis",
        "commercial-loan-retrieval-agent",
        "commercial-loan-servicing-qa",
        "human-review-required",
    ),
}

SEARCH_TERMS = {
    "salesforce-edge": "care center call center customer service fee reversal knowledge article",
    "seismic-sales-content": "treasury seller sales collateral cash management",
    "pinnacle-product-docs": "treasury product documentation cash management positive pay ach",
    "qvidian-proposal-library": "treasury rfp proposal response reusable answers",
    "midland-loan-documents": "commercial loan agreement borrower insurance covenant collateral flood",
    "commercial-loan-profile": "loan servicing borrower profile insurance review",
    "insurance-policy-standards": "insurance servicing procedure policy standards flood",
    "azure-search-rag": "retrieval augmented generation enterprise search semantic retrieval",
    "grounded-covenant-analysis": "insurance covenant citation grounded finding human review",
    "commercial-loan-retrieval-agent": "commercial loan document retrieval insurance covenant",
    "treasury-sales-assistant": "treasury seller rfp proposal cash management sales assistant",
    "retail-care-center-assist": "retail care center call center fee reversal customer service",
    "commercial-loan-servicing-qa": "commercial loan servicing insurance covenant document question",
}

NEW_NODES = (
    (
        "treasury-sales-rag-agent",
        "Treasury Sales Retrieval Agent",
        "Registered retrieval instance used by the existing treasury sales workflow.",
        "Treasury Management",
        "internal",
        "treasury_management",
        "treasury sales rfp proposal cash management retrieval",
    ),
    (
        "retail-care-rag-agent",
        "Retail Care Retrieval Agent",
        "Registered retrieval instance used by the existing retail care-center workflow.",
        "Retail Banking",
        "internal",
        "retail_banking",
        "retail care center customer service knowledge retrieval",
    ),
)

NEW_EDGES = (
    ("treasury-sales-assistant", "uses", "treasury-sales-rag-agent"),
    ("retail-care-center-assist", "uses", "retail-care-rag-agent"),
    ("treasury-sales-rag-agent", "instance_of", "azure-search-rag"),
    ("retail-care-rag-agent", "instance_of", "azure-search-rag"),
    ("commercial-loan-retrieval-agent", "instance_of", "azure-search-rag"),
    ("treasury-sales-rag-agent", "reads", "seismic-sales-content"),
    ("treasury-sales-rag-agent", "reads", "pinnacle-product-docs"),
    ("treasury-sales-rag-agent", "reads", "qvidian-proposal-library"),
    ("retail-care-rag-agent", "reads", "salesforce-edge"),
    ("commercial-loan-retrieval-agent", "reads", "midland-loan-documents"),
)


def enrich_catalog(apps, schema_editor):
    OntologyNode = apps.get_model("studio", "OntologyNode")
    OntologyEdge = apps.get_model("studio", "OntologyEdge")

    for domain, slugs in DOMAIN_SLUGS.items():
        OntologyNode.objects.filter(slug__in=slugs).update(business_domain=domain)
    for slug, search_terms in SEARCH_TERMS.items():
        OntologyNode.objects.filter(slug=slug).update(search_terms=search_terms)

    for slug, name, description, owner, classification, domain, search_terms in NEW_NODES:
        OntologyNode.objects.update_or_create(
            slug=slug,
            defaults={
                "node_type": "agent_instance",
                "name": name,
                "description": description,
                "owner": owner,
                "classification": classification,
                "approval_state": "approved",
                "source_reference": "V3 agent instance",
                "business_domain": domain,
                "search_terms": search_terms,
            },
        )

    nodes = OntologyNode.objects.in_bulk(field_name="slug")
    for source_slug, relation, target_slug in NEW_EDGES:
        OntologyEdge.objects.get_or_create(
            source=nodes[source_slug],
            relation=relation,
            target=nodes[target_slug],
            defaults={
                "rationale": (
                    "Catalog relationship added to make the registered domain path "
                    "explicit for explainable discovery."
                )
            },
        )


def remove_catalog_enrichment(apps, schema_editor):
    OntologyNode = apps.get_model("studio", "OntologyNode")
    OntologyEdge = apps.get_model("studio", "OntologyEdge")
    node_ids = dict(OntologyNode.objects.values_list("slug", "id"))
    for source_slug, relation, target_slug in NEW_EDGES:
        OntologyEdge.objects.filter(
            source_id=node_ids.get(source_slug),
            relation=relation,
            target_id=node_ids.get(target_slug),
        ).delete()
    OntologyNode.objects.filter(slug__in=[node[0] for node in NEW_NODES]).delete()
    OntologyNode.objects.update(business_domain="enterprise", search_terms="")


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_backfill_agent_manifests'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologynode',
            name='business_domain',
            field=django_enum.fields.EnumCharField(choices=[('enterprise', 'Enterprise / shared'), ('treasury_management', 'Treasury management'), ('retail_banking', 'Retail banking'), ('commercial_loan_servicing', 'Commercial loan servicing')], db_comment='Business domain responsible for using or governing the concept.', default='enterprise', help_text='Domain used to scope discovery and route accountable ownership.', max_length=40),
        ),
        migrations.AddField(
            model_name='ontologynode',
            name='search_terms',
            field=models.TextField(blank=True, db_comment='Curated synonyms and business phrases used for explainable discovery.', help_text='Add plain-language terms requesters may use for this concept. Do not add customer data.'),
        ),
        migrations.RunPython(enrich_catalog, remove_catalog_enrichment),
        migrations.AddIndex(
            model_name='ontologynode',
            index=models.Index(fields=['business_domain', 'approval_state'], name='studio_onto_busines_6ee709_idx'),
        ),
        migrations.AddConstraint(
            model_name='ontologynode',
            constraint=models.CheckConstraint(condition=models.Q(('business_domain__in', ['enterprise', 'treasury_management', 'retail_banking', 'commercial_loan_servicing'])), name='studio_OntologyNode_business_domain_BusinessDomain'),
        ),
    ]
